import type { Locale } from "@/i18n/config";

/**
 * Every word in the admin console, in both languages, in one file.
 *
 * The parent-facing app keeps its copy in src/i18n/dictionaries.ts. The console
 * is a separate audience with a separate vocabulary — "draft", "funnel",
 * "audit" — and mixing the two made the parent dictionary hard to read.
 */

// Deliberately not `as const`. With it, every Indonesian string becomes its own
// literal type and the English object cannot satisfy the shape — "Overview" is
// not assignable to "Ringkasan". The parent dictionary hit the same trap.
const ID = {
  nav: {
    overview: "Ringkasan",
    content: "Konten",
    activities: "Aktivitas",
    stories: "Cerita",
    bonding: "Momen bonding",
    worksheets: "Lembar kerja",
    audio: "Audio",
    users: "Pengguna",
    orders: "Pesanan",
    subscriptions: "Langganan",
    settings: "Pengaturan",
    audit: "Jejak audit",
    backToApp: "Buka aplikasi",
  },
  common: {
    search: "Cari",
    searchPlaceholder: "Cari judul atau id…",
    save: "Simpan",
    saving: "Menyimpan…",
    saved: "Tersimpan",
    cancel: "Batal",
    edit: "Ubah",
    create: "Buat baru",
    duplicate: "Duplikat",
    delete: "Hapus",
    publish: "Tayangkan",
    unpublish: "Tarik dari tayang",
    archive: "Arsipkan",
    status: "Status",
    all: "Semua",
    none: "—",
    of: "dari",
    rows: "baris",
    noResults: "Tidak ada yang cocok dengan filter ini.",
    noResultsLead: "Ubah kata kunci atau kosongkan filternya.",
    required: "wajib",
    optional: "opsional",
    back: "Kembali",
    problems: "Belum bisa ditayangkan",
    yes: "Ya",
    no: "Tidak",
    adminOnly: "Hanya admin yang bisa melakukan ini.",
    editorNotice:
      "Anda masuk sebagai editor: bisa menulis dan menyunting draf, tetapi hanya admin yang bisa menayangkan atau menyetujui pembayaran.",
    confirm: "Yakin?",
    minutes: "menit",
    updated: "Diperbarui",
    created: "Dibuat",
    locale: { id: "Bahasa Indonesia", en: "English" },
  },
  status: {
    draft: "Draf",
    review: "Ditinjau",
    published: "Tayang",
    retired: "Diarsipkan",
  },
  overview: {
    title: "Ringkasan",
    lead: "Angka hari ini, dibandingkan periode sebelumnya.",
    parents: "Orang tua",
    children: "Anak terdaftar",
    activeSubs: "Langganan aktif",
    mrr: "Perkiraan pendapatan bulanan",
    revenue30: "Uang masuk 30 hari",
    completions: "Aktivitas selesai, 7 hari",
    signups: "Pendaftar, 7 hari",
    aiQuestions: "Pertanyaan AI bulan ini",
    pending: "Pesanan menunggu",
    trend: "30 hari terakhir",
    trendSignups: "Pendaftar",
    trendCompletions: "Aktivitas selesai",
    funnel: "Perjalanan orang tua, 30 hari",
    funnelLead:
      "Yang penting bukan angka paling atas, melainkan di mana orang tua berhenti.",
    funnelSteps: {
      signed_up: "Mendaftar",
      added_child: "Menambah profil anak",
      did_one: "Satu aktivitas selesai",
      did_three: "Tiga aktivitas selesai",
      started_order: "Membuka pembayaran",
      paid: "Berlangganan",
    },
    topActivities: "Aktivitas paling sering dilakukan",
    topActivitiesLead: "30 hari terakhir.",
    coverage: "Sebaran domain",
    coverageLead:
      "Kolom kanan yang kosong berarti kontennya ada tetapi belum terpakai.",
    coveragePublished: "Tayang",
    coverageUsed: "Dilakukan",
    todo: "Perlu ditangani",
    todoClear: "Tidak ada yang perlu ditangani. Semuanya rapi.",
    todoOrders: (n: number) => `${n} pesanan menunggu verifikasi transfer.`,
    todoBank:
      "Rekening tujuan belum diisi, jadi layar pembayaran masih disembunyikan.",
    todoSafety: (n: number) =>
      `${n} aktivitas tayang tanpa catatan keamanan yang lengkap.`,
    todoTranslation: (n: number) => `${n} aktivitas belum lengkap dua bahasanya.`,
    todoAudio: (n: number) => `${n} trek audio belum punya berkas.`,
    todoDraft: (n: number) => `${n} aktivitas masih draf.`,
    vsPrev: "vs periode sebelumnya",
  },
  content: {
    title: "Konten",
    lead: "Database adalah sumber kebenarannya. Berkas JSON di content/ adalah cadangan.",
    activitiesTitle: "Aktivitas",
    storiesTitle: "Cerita",
    bondingTitle: "Momen bonding",
    worksheetsTitle: "Lembar kerja",
    audioTitle: "Audio",
    filterAge: "Kelompok usia",
    filterDomain: "Domain",
    filterStatus: "Status",
    filterPremium: "Akses",
    premiumOnly: "Premium",
    freeOnly: "Gratis",
    colTitle: "Judul",
    colAge: "Usia",
    colDomain: "Domain",
    colDuration: "Durasi",
    colStatus: "Status",
    colUpdated: "Diperbarui",
    colPages: "Halaman",
    colType: "Jenis",
    colFile: "Berkas",
    newActivity: "Aktivitas baru",
    newStory: "Cerita baru",
    newBonding: "Momen baru",
    bothLocales: "Dua bahasa wajib diisi, dengan jumlah langkah yang sama.",
    stepsHead: "Langkah",
    addStep: "Tambah langkah",
    removeStep: "Hapus",
    stepTitle: "Judul langkah",
    stepBody: "Isi langkah",
    pagesHead: "Halaman",
    addPage: "Tambah halaman",
    pageText: "Teks halaman",
    safety: "Catatan keamanan",
    safetyHelp:
      "Wajib untuk aktivitas yang memakai bahan atau untuk bayi di bawah 12 bulan.",
    variations: "Variasi",
    variationsHelp: "Satu variasi per baris.",
    parentTip: "Tips untuk orang tua",
    materialsText: "Daftar bahan (teks)",
    materials: "Bahan",
    materialsHelp: "Pilih dari daftar bahan rumah tangga yang dikenal sistem.",
    learningGoal: "Tujuan belajar",
    summary: "Ringkasan",
    titleField: "Judul",
    blurb: "Sinopsis",
    prompt: "Yang dilakukan orang tua",
    whyItMatters: "Mengapa ini penting",
    theme: "Tema",
    interactive: "Interaktif",
    readingMinutes: "Lama membaca",
    momentType: "Jenis momen",
    ageMin: "Usia minimum (bulan)",
    ageMax: "Usia maksimum (bulan)",
    ageBand: "Kelompok usia",
    primaryDomain: "Domain utama",
    secondaryDomains: "Domain pendukung",
    skills: "Keterampilan",
    duration: "Durasi (menit)",
    difficulty: "Tingkat kesulitan",
    bondingLevel: "Kedekatan",
    musicMode: "Mode musik",
    premium: "Hanya untuk Premium",
    needsSupervision: "Perlu pendampingan",
    screenFree: "Tanpa layar",
    illustration: "Ilustrasi",
    audioUpload: "Unggah MP3",
    audioMissing: "Belum ada berkas",
    audioPreview: "Dengarkan",
    audioKind: "Jenis",
    exportTitle: "Cadangkan ke JSON",
    exportLead:
      "Mengunduh seluruh konten dalam format yang sama dengan content/, untuk disimpan di git.",
    exportButton: "Unduh cadangan",
  },
  users: {
    title: "Pengguna",
    lead: "Satu baris per orang tua, dengan paket dan aktivitas terakhirnya.",
    colName: "Nama",
    colEmail: "Email",
    colRole: "Peran",
    colPlan: "Paket",
    colChildren: "Anak",
    colCompletions: "Aktivitas",
    colLastSeen: "Terakhir aktif",
    colJoined: "Bergabung",
    roleParent: "Orang tua",
    roleEditor: "Editor",
    roleAdmin: "Admin",
    changeRole: "Ubah peran",
    grantPremium: "Beri Premium",
    grantMonths: "Berapa lama",
    grantNote: "Catatan",
    grantDo: "Berikan",
    children: "Anak",
    childrenLead: "Nama dan tanggal lahir, sesuai yang diisi orang tua.",
    lastAdmin: "Ini admin terakhir, perannya tidak bisa dilepas.",
  },
  orders: {
    title: "Pesanan",
    lead: "Transfer manual diverifikasi di sini. Akses berubah hanya setelah disetujui.",
    colRef: "Kode",
    colParent: "Orang tua",
    colPlan: "Paket",
    colTotal: "Jumlah transfer",
    colStatus: "Status",
    colCreated: "Dibuat",
    colReviewed: "Diperiksa",
    statusLabels: {
      awaiting_payment: "Menunggu transfer",
      awaiting_confirmation: "Menunggu verifikasi",
      paid: "Lunas",
      rejected: "Ditolak",
      expired: "Kedaluwarsa",
      cancelled: "Dibatalkan",
    },
    empty: "Belum ada pesanan.",
    emptyLead: "Pesanan yang sudah ditransfer orang tua akan muncul di sini.",
    suffixNote:
      "Jumlah transfer berakhiran tiga angka unik. Angka itulah penanda pesanannya, jangan dibulatkan.",
    revenue: "Pendapatan per bulan",
  },
  subscriptions: {
    title: "Langganan",
    lead: "Satu langganan aktif per orang tua.",
    colPlan: "Paket",
    colStatus: "Status",
    colStarted: "Mulai",
    colExpires: "Berakhir",
    colProvider: "Sumber",
    cancel: "Hentikan",
    extend: "Perpanjang",
    empty: "Belum ada langganan aktif.",
    emptyLead: "Langganan muncul setelah sebuah pesanan disetujui.",
  },
  settings: {
    title: "Pengaturan",
    lead: "Semua nilai di sini tersimpan di database, jadi berubah tanpa deploy ulang.",
    bankTitle: "Rekening penerima",
    bankLead:
      "Layar pembayaran tetap disembunyikan sampai ketiga kolom ini terisi, supaya aplikasi tidak pernah menampilkan nomor rekening yang tidak ada.",
    priceTitle: "Harga",
    priceLead: "Dalam rupiah, tanpa titik.",
    freeTitle: "Batas paket gratis",
    freeLead: "Kosongkan artinya nol, bukan tanpa batas.",
    featureTitle: "Sakelar fitur",
    featureLead:
      "Mematikan sebuah fitur menyembunyikannya sepenuhnya, bukan menampilkan tombol yang tidak berfungsi.",
    on: "Aktif",
    off: "Mati",
  },
  audit: {
    title: "Jejak audit",
    lead: "Siapa menyetujui pesanan, mengubah peran, menayangkan konten, dan mengganti pengaturan.",
    colWhen: "Waktu",
    colWho: "Oleh",
    colWhat: "Tindakan",
    colObject: "Objek",
    colSummary: "Keterangan",
    empty: "Belum ada catatan.",
    emptyLead: "Setiap tindakan admin akan tercatat di sini.",
  },
};

type AdminCopy = typeof ID;

const EN: AdminCopy = {
  nav: {
    overview: "Overview",
    content: "Content",
    activities: "Activities",
    stories: "Stories",
    bonding: "Bonding moments",
    worksheets: "Worksheets",
    audio: "Audio",
    users: "People",
    orders: "Orders",
    subscriptions: "Subscriptions",
    settings: "Settings",
    audit: "Audit trail",
    backToApp: "Open the app",
  },
  common: {
    search: "Search",
    searchPlaceholder: "Search a title or id…",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    cancel: "Cancel",
    edit: "Edit",
    create: "New",
    duplicate: "Duplicate",
    delete: "Delete",
    publish: "Publish",
    unpublish: "Unpublish",
    archive: "Archive",
    status: "Status",
    all: "All",
    none: "—",
    of: "of",
    rows: "rows",
    noResults: "Nothing matches these filters.",
    noResultsLead: "Change the search or clear the filters.",
    required: "required",
    optional: "optional",
    back: "Back",
    problems: "Not ready to publish",
    yes: "Yes",
    no: "No",
    adminOnly: "Only an admin can do this.",
    editorNotice:
      "You're signed in as an editor: you can write and revise drafts, but only an admin can publish or confirm a payment.",
    confirm: "Are you sure?",
    minutes: "min",
    updated: "Updated",
    created: "Created",
    locale: { id: "Bahasa Indonesia", en: "English" },
  },
  status: {
    draft: "Draft",
    review: "In review",
    published: "Published",
    retired: "Archived",
  },
  overview: {
    title: "Overview",
    lead: "Today's figures, against the period before.",
    parents: "Parents",
    children: "Children",
    activeSubs: "Active subscriptions",
    mrr: "Estimated monthly revenue",
    revenue30: "Money in, 30 days",
    completions: "Activities done, 7 days",
    signups: "Sign-ups, 7 days",
    aiQuestions: "AI questions this month",
    pending: "Orders waiting",
    trend: "Last 30 days",
    trendSignups: "Sign-ups",
    trendCompletions: "Activities done",
    funnel: "What parents do, 30 days",
    funnelLead: "The top number matters less than where parents stop.",
    funnelSteps: {
      signed_up: "Signed up",
      added_child: "Added a child",
      did_one: "Finished one activity",
      did_three: "Finished three activities",
      started_order: "Opened checkout",
      paid: "Subscribed",
    },
    topActivities: "Most completed activities",
    topActivitiesLead: "Last 30 days.",
    coverage: "Domain coverage",
    coverageLead: "An empty right column means content exists but nobody uses it.",
    coveragePublished: "Published",
    coverageUsed: "Completed",
    todo: "Needs attention",
    todoClear: "Nothing needs attention. All clear.",
    todoOrders: (n: number) => `${n} order(s) waiting for a transfer to be confirmed.`,
    todoBank: "No bank account is set, so the payment screen is still hidden.",
    todoSafety: (n: number) => `${n} published activity(s) have an incomplete safety note.`,
    todoTranslation: (n: number) => `${n} activity(s) are missing a translation.`,
    todoAudio: (n: number) => `${n} audio track(s) have no file.`,
    todoDraft: (n: number) => `${n} activity(s) are still drafts.`,
    vsPrev: "vs the period before",
  },
  content: {
    title: "Content",
    lead: "The database is the source of truth. The JSON under content/ is a backup.",
    activitiesTitle: "Activities",
    storiesTitle: "Stories",
    bondingTitle: "Bonding moments",
    worksheetsTitle: "Worksheets",
    audioTitle: "Audio",
    filterAge: "Age band",
    filterDomain: "Domain",
    filterStatus: "Status",
    filterPremium: "Access",
    premiumOnly: "Premium",
    freeOnly: "Free",
    colTitle: "Title",
    colAge: "Age",
    colDomain: "Domain",
    colDuration: "Length",
    colStatus: "Status",
    colUpdated: "Updated",
    colPages: "Pages",
    colType: "Type",
    colFile: "File",
    newActivity: "New activity",
    newStory: "New story",
    newBonding: "New moment",
    bothLocales: "Both languages are mandatory, with the same number of steps.",
    stepsHead: "Steps",
    addStep: "Add a step",
    removeStep: "Remove",
    stepTitle: "Step title",
    stepBody: "Step body",
    pagesHead: "Pages",
    addPage: "Add a page",
    pageText: "Page text",
    safety: "Safety note",
    safetyHelp:
      "Required for an activity with materials, or for a baby under twelve months.",
    variations: "Variations",
    variationsHelp: "One variation per line.",
    parentTip: "Tip for the parent",
    materialsText: "Materials, written out",
    materials: "Materials",
    materialsHelp: "Pick from the household materials the system knows.",
    learningGoal: "Learning goal",
    summary: "Summary",
    titleField: "Title",
    blurb: "Blurb",
    prompt: "What the parent does",
    whyItMatters: "Why it matters",
    theme: "Theme",
    interactive: "Interactive",
    readingMinutes: "Reading time",
    momentType: "Moment",
    ageMin: "Minimum age (months)",
    ageMax: "Maximum age (months)",
    ageBand: "Age band",
    primaryDomain: "Primary domain",
    secondaryDomains: "Supporting domains",
    skills: "Skills",
    duration: "Length (minutes)",
    difficulty: "Difficulty",
    bondingLevel: "Closeness",
    musicMode: "Music mode",
    premium: "Premium only",
    needsSupervision: "Needs supervision",
    screenFree: "Screen-free",
    illustration: "Illustration",
    audioUpload: "Upload an MP3",
    audioMissing: "No file yet",
    audioPreview: "Listen",
    audioKind: "Kind",
    exportTitle: "Back up to JSON",
    exportLead:
      "Downloads the whole library in the same shape as content/, to keep in git.",
    exportButton: "Download the backup",
  },
  users: {
    title: "People",
    lead: "One row per parent, with their plan and their last activity.",
    colName: "Name",
    colEmail: "Email",
    colRole: "Role",
    colPlan: "Plan",
    colChildren: "Children",
    colCompletions: "Activities",
    colLastSeen: "Last seen",
    colJoined: "Joined",
    roleParent: "Parent",
    roleEditor: "Editor",
    roleAdmin: "Admin",
    changeRole: "Change role",
    grantPremium: "Grant Premium",
    grantMonths: "How long",
    grantNote: "Note",
    grantDo: "Grant",
    children: "Children",
    childrenLead: "Names and birth dates, as the parent entered them.",
    lastAdmin: "This is the last admin, so the role cannot be removed.",
  },
  orders: {
    title: "Orders",
    lead: "Manual transfers are confirmed here. Nothing about access changes until one is approved.",
    colRef: "Reference",
    colParent: "Parent",
    colPlan: "Plan",
    colTotal: "Transfer amount",
    colStatus: "Status",
    colCreated: "Created",
    colReviewed: "Reviewed",
    statusLabels: {
      awaiting_payment: "Awaiting transfer",
      awaiting_confirmation: "Awaiting confirmation",
      paid: "Paid",
      rejected: "Rejected",
      expired: "Expired",
      cancelled: "Cancelled",
    },
    empty: "No orders yet.",
    emptyLead: "Orders a parent has paid for will appear here.",
    suffixNote:
      "The transfer amount ends in three unique digits. That figure is the order's identifier, so never round it away.",
    revenue: "Revenue by month",
  },
  subscriptions: {
    title: "Subscriptions",
    lead: "One active subscription per parent.",
    colPlan: "Plan",
    colStatus: "Status",
    colStarted: "Started",
    colExpires: "Ends",
    colProvider: "Source",
    cancel: "Stop",
    extend: "Extend",
    empty: "No active subscriptions yet.",
    emptyLead: "A subscription appears once an order is approved.",
  },
  settings: {
    title: "Settings",
    lead: "Everything here is stored in the database, so it changes without a redeploy.",
    bankTitle: "Receiving account",
    bankLead:
      "The payment screen stays hidden until all three fields are filled, so the app never shows an account number it does not have.",
    priceTitle: "Pricing",
    priceLead: "In rupiah, digits only.",
    freeTitle: "Free-tier limits",
    freeLead: "Empty means zero, not unlimited.",
    featureTitle: "Feature switches",
    featureLead:
      "Switching a feature off hides it completely rather than showing a control that does nothing.",
    on: "On",
    off: "Off",
  },
  audit: {
    title: "Audit trail",
    lead: "Who approved an order, changed a role, published content, or changed a setting.",
    colWhen: "When",
    colWho: "By",
    colWhat: "Action",
    colObject: "Object",
    colSummary: "Detail",
    empty: "Nothing recorded yet.",
    emptyLead: "Every admin action is recorded here.",
  },
};

export function adminCopy(locale: Locale): AdminCopy {
  return locale === "en" ? EN : ID;
}

export type { AdminCopy };
